### ISSUE TITLE
Malformed Installer

### ISSUE THREAD

**Issue by chrisspen** [bioidiap/bob.blitz#3]
The PIP package bob.blitz is uninstallable because the required package list appears to contain a circular dependency:

    $ virtualenv --no-site-packages .env
    $ . .env/bin/activate
    (.env)$ pip install -U pip
    (.env)$ pip install numpy
    (...snip numpy installation output...)
    (.env)$ pip install bob.blitz
    Collecting bob.blitz
      Using cached bob.blitz-2.0.7.zip
        Complete output from command python setup.py egg_info:
        
        Installed /tmp/pip-build-rHBzDo/bob.blitz/bob.extension-2.0.8-py2.7.egg
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/tmp/pip-build-rHBzDo/bob.blitz/setup.py", line 74, in <module>
            system_include_dirs=system_include_dirs,
          File "/tmp/pip-build-rHBzDo/bob.blitz/bob.extension-2.0.8-py2.7.egg/bob/extension/__init__.py", line 365, in __init__
            pkgs = check_packages(packages)
          File "/tmp/pip-build-rHBzDo/bob.blitz/bob.extension-2.0.8-py2.7.egg/bob/extension/__init__.py", line 57, in check_packages
            p = pkgconfig(splitreq[0])
          File "/tmp/pip-build-rHBzDo/bob.blitz/bob.extension-2.0.8-py2.7.egg/bob/extension/pkgconfig.py", line 131, in __init__
            raise RuntimeError("pkg-config package `%s' was not found" % name)
        RuntimeError: pkg-config package `blitz' was not found

I tried installed the [blitz](https://pypi.python.org/pypi/blitz/0.3.3) package separately, thinking that was the dependency, but that did not fix the problem.

Note, this problem effectively makes all bob.* PIP packages uninstallable since they all appear to require this package. My original objective was to test bob.spear, which I can't do until I find a fix for this.

**Comment by tiagofrepereira2012** [comment]
Hi Chris,

Which OS are you using?
In this link "https://github.com/idiap/bob/wiki/Dependencies" you can find the list of dependencies of the Bob python packages that you should install.

For instance, to install blitz library on Ubuntu you should do:
```sudo apt-get install libblitz0-dev```

Any other issue, let me know

Cheers

Tiago

**Comment by anjos** [comment]
As Tiago suggested, I think this issue relates to a malformed/incomplete blitz++ installation. Make sure you install development packages and that blitz.pc (the pkg-config file associated) is among them. Otherwise, bob.blitz cannot "sense" blitz++ is installed.

As a note, it is probably better to take-up this kind of discussions in our dev group: 
https://groups.google.com/forum/?fromgroups#!forum/bob-devel

The discussion may help other parties with similar problems.

**Comment by chrisspen** [comment]
I'm using Ubuntu 14.04. Yes, installing libblitz0-dev seemed to fix that problem. But now I'm getting a similar error when I try and install bob.spear inside a virtualenv wiht pip:

     No package 'bob-python' found

What's causing this error? There's no such package in Ubuntu's standard repo and I don't see it listed in the dependencies you linked to.

**Comment by anjos** [comment]
Could you please post the command and the failing logs? It is difficult to debug w/o more information.

**Comment by chrisspen** [comment]
(.env)$ pip install bob.spear
    Collecting bob.spear
    /usr/local/myproject/.env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
      InsecurePlatformWarning
      Downloading bob.spear-1.1.8.zip (1.8MB)
        100% |████████████████████████████████| 1.8MB 153kB/s 
    Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/myproject/.env/lib/python2.7/site-packages (from bob.spear)
    Collecting gridtk>=1.0.3 (from bob.spear)
      Using cached gridtk-1.2.2.zip
    Collecting bob>=1.2.0 (from bob.spear)
      Using cached bob-2.0.5.zip
    Collecting facereclib<2.0.0 (from bob.spear)
      Downloading facereclib-1.2.3.zip (6.6MB)
        100% |████████████████████████████████| 6.6MB 50kB/s 
    Collecting xbob.db.verification.filelist (from bob.spear)
      Using cached xbob.db.verification.filelist-1.3.5.zip
    Collecting xbob.db.voxforge (from bob.spear)
      Using cached xbob.db.voxforge-0.1.0.zip
    Collecting xbob.sox (from bob.spear)
      Using cached xbob.sox-1.1.0.zip
        Complete output from command python setup.py egg_info:
        
        Installed /tmp/pip-build-RJ4aKr/xbob.sox/xbob.extension-0.2.1-py2.7.egg
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/tmp/pip-build-RJ4aKr/xbob.sox/setup.py", line 72, in <module>
            "sox",
          File "build/bdist.linux-x86_64/egg/xbob/extension/__init__.py", line 168, in __init__
          File "build/bdist.linux-x86_64/egg/xbob/extension/__init__.py", line 48, in pkgconfig
        RuntimeError: PkgConfig did not find package bob-python. Output:
        Package bob-python was not found in the pkg-config search path.
        Perhaps you should add the directory containing `bob-python.pc'
        to the PKG_CONFIG_PATH environment variable
        No package 'bob-python' found
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-RJ4aKr/xbob.sox

**Comment by anjos** [comment]
I'm not an expert in bob.spear, but it seems you're trying to install a package that relies on bob v1. In this case, please note you can't do it with pip. Furthermore, note bob v1 is being phased-out and not supported on Ubuntu 14.04. IMO, you should be trying to use "bob.bio.spear" instead, which is the version of bob.spear that is compatible to your bob v2 environment you just setup. Please move this question, with the logs to our group mailing list. Someone else will pick it up. I'll close this here since it does not concern bob.blitz anymore.
