### ISSUE TITLE
constness is not assured in PyBlitzArray_NUMPY_WRAP

### ISSUE THREAD

**Issue by siebenkopf** [bioidiap/bob.blitz#6]
When we need to return a const numpy array wrapper around a blitz array (as modifying it would lead to inconsistencies, see https://github.com/idiap/bob/issues/220), we'd like to use the ``PyBlitzArrayCxx_AsConstNumpy`` function. Indeed, this function sets the constness flag of the blitz array inside ``PyBlitzArrayCxx_NewFromConstArray``:
https://github.com/bioidiap/bob.blitz/blob/master/bob/blitz/include/bob.blitz/cppapi.h#L192
However, the wrapping function ``PyBlitzArray_NUMPY_WRAP`` does not copy that flag and, consequently, the returned ``numpy.ndarray`` is writeable.

I have just added a test case that checks exactly that. Currently it fails.
@anjos: As you wrote that function and you are most familiar with the NumPy C-API, could you please have a look into that? Could you also verify that there are no other flags that need to be copied, too?

**Comment by anjos** [comment]
I'm a bit overloaded with other things right now - I'm happy to review a pull request though.

**Comment by siebenkopf** [comment]
@anjos: I don't think that there are more flags to be set, except for the ``writeable`` flag. I have pushed some code that sets the flags appropriately when creating the ``PyArrayObject``, and I think this should be fine now. However, your opinion about this is highly welcome, see: https://github.com/bioidiap/bob.blitz/commit/dc668b11306961f6c310738cf68c42eca8827df2

**Comment by anjos** [comment]
The patch looks good - thanks. My only doubt was the return line. Before, we were returning retval, now you're building a new reference. Are you confident you're not incref'ing too much?

**Comment by siebenkopf** [comment]
I think that this should be fine. I have added a ``make_safe`` on ``retval`` before, so ``INCREF``'ing should be fine.

**Comment by anjos** [comment]
Good for me then! Thanks once more, A

**Comment by siebenkopf** [comment]
It is just that we have to correct some other packages now, which are returning const arrays, where they should not. At least it seems that there are some test in ``bob.nightlies`` failing now.
